### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by bromar2292** [SchoolOfCode/final-project-app-eco-warriors#3]
- [x] Business/personal selection
- [x] input for personal
- [x] input for business
