### ISSUE TITLE
Footer - 

### ISSUE THREAD

**Issue by bromar2292** [SchoolOfCode/final-project-app-eco-warriors#5]
- [ ] Create a Footer Component. This will be split in 3 boxes: 
       - [ ] Home - it will say "home" and have a little icon (placeholder)
      - [ ] Interests - it will say "interests" and have a little I icon maybe (placeholder) 
     - [ ] QR - it will have a little picture of a QR code
