### ISSUE TITLE
QR Component

### ISSUE THREAD

**Issue by bromar2292** [SchoolOfCode/final-project-app-eco-warriors#7]
- [ ] Full page

- [x] users backend stage 1
- [x] users backend stage 2

- [x] business backend stage 1
- [x] business backend stage 2
