### ISSUE TITLE
design/theme

### ISSUE THREAD

**Issue by bromar2292** [SchoolOfCode/final-project-app-eco-warriors#8]
- [ ] Decide color scheme 
   - [ ] Deside design
   - [ ] Create logo 
   - [ ] Font 

 - [ ] Register
     - [ ] Businiess/personal design
     - [ ] Input field design

 - [ ] Top menu title 
    - [ ] Setting icons
    - [ ] Title icon

 - [ ] Interestes page
   - [ ] Drop down styleing
   - [ ] Display of content styeling 

- [ ] Footer menu
   - [ ] Icon for home
  - [ ] Icon for interests
  - [ ] Icon for qr code
